#!/bin/bash
cwd=$(pwd)
mkdir Keras-examples
cd Keras-examples/ && \
git init && \
git remote add origin -f https://github.com/fchollet/keras && \
git config core.sparsecheckout true && \
echo "examples/*" >> .git/info/sparse-checkout && \
git pull --depth=2 origin master
cd $cwd
nvidia-docker build -f Docker/Dockerfile       --rm=true -t emsi/dl_training .
