#!/bin/bash

#GPU='--accelerator type=nvidia-tesla-k80,count=1'
GPU='--accelerator type=nvidia-tesla-k80,count=1'
#TYPE='--machine-type n1-standard-16 --zone us-east1-d' 
TYPE='--machine-type n1-standard-8 --zone us-east1-d'


gcloud beta compute instances create gpu-instance-1 \
    $TYPE \
    $GPU \
    --address 35.196.139.97 \
    --boot-disk-size "80" --boot-disk-type "pd-ssd" \
    --image-family ubuntu-1604-lts --image-project ubuntu-os-cloud \
    --maintenance-policy TERMINATE --restart-on-failure \
    --metadata-from-file startup-script=install.sh \
    --tags "http-server","https-server"

gcloud compute --project=compute-project-1 firewall-rules create default-allow-http --network=default --action=ALLOW --rules=tcp:80 --source-ranges=0.0.0.0/0 --target-tags=http-server
gcloud compute --project=compute-project-1 firewall-rules create default-allow-https --network=default --action=ALLOW --rules=tcp:443 --source-ranges=0.0.0.0/0 --target-tags=https-server
