#!/bin/bash

#GPU='--accelerator type=nvidia-tesla-k80,count=1'
GPU='--accelerator type=nvidia-tesla-k80,count=1'
#TYPE='--machine-type n1-standard-16 --zone us-east1-d' 
TYPE='--machine-type n1-standard-4 --zone us-east1-d'


gcloud beta compute instances create gpu-instance-1 \
    $TYPE \
    $GPU \
    --address 35.196.139.97 \
    --boot-disk-size "80" --boot-disk-type "pd-ssd" \
    --image-family ubuntu-1604-lts --image-project ubuntu-os-cloud \
    --maintenance-policy TERMINATE --restart-on-failure \
    --metadata-from-file startup-script=install.sh
